name = "gordianweblanding"
main = "simple-worker.js"
compatibility_date = "2024-07-28"
workers_dev = true
account_id = "97c584926edd1917b51cac84d7aae155"

[observability.logs]
enabled = true

[[routes]]
pattern = "gordiandev.io/*"
zone_name = "gordiandev.io"

[[routes]]
pattern = "www.gordiandev.io/*"
zone_name = "gordiandev.io"